// const db = require("../database/db.json");
const models = require("../database/models");

const cadastraFilme = async (req, res) => {
  try {
    const data = await models.Filme.findOne({ where: { cod: req.body.id } });

    if (data) {
      return res.status(400).json();
    }

    const nFilme = {
      cod: req.body.id,
      titulo: req.body.titulo,
      sinopse: req.body.sinopse,
      ano: req.body.ano,
      direcao: req.body.direcao,
      generos: req.body.generos,
      duracao: req.body.duracao,
      id_produtora: req.body.id_produtora,
    };

    const filme = await models.Filme.create(nFilme);
    return res.status(201).json(filme);
  } catch (error) {
    const filmes_obj = Object.keys(models.Filme.rawAttributes)
      .filter((key) => !models.Filme.rawAttributes[key]._autoGenerated)
      .map((key) => {
        return {
          field: models.Filme.rawAttributes[key].field,
          type: models.Filme.rawAttributes[key].type.key,
          optional: models.Filme.rawAttributes[key].allowNull !== false,
        };
      });
    if (error instanceof models.Sequelize.DatabaseError) {
      return res.status(400).json({
        error: error.message,
        expected_json: filmes_obj,
      });
    } else {
      return res.status(400).json({});
    }
  }
};

const listaFilmes = async (req, res) => {
  const data = await models.Filme.findAll({});

  const filmes = data.map((filme) => {
    const values = filme.dataValues;
    values.id = values.cod;
    delete values.cod;
    filme.direcao = filme.direcao.join(", ");
    return {
      ...values,
      url: `https://www.youtube.com/watch?v=${filme.cod}`,
    };
  });

  return res.status(200).json(filmes);
};

const buscaFilmeById = async (req, res) => {
  const filmeId = req.params.filmeId;

  const data = await models.Filme.findOne({ where: { cod: filmeId } });

  if (!data) {
    return res.status(404).json("Not Found");
  }

  const values = data.dataValues;
  values.id = values.cod;
  delete values.cod;

  values.direcao = values.direcao.join(", ");

  const filme = {
    ...values,
    url: `https://www.youtube.com/watch?v=${data.cod}`,
  };

  if (filme) {
    return res.status(200).json(filme);
  }

  return res.status(404).send(new Error("Not Found"));
};

const buscaFilmesPelaProdutora = async (req, res) => {
  const id_produtora = req.params.id_produtora;

  const data = await models.Filme.findAll({
    where: { id_produtora: id_produtora },
  });

  const filmes = data.map((filme) => {
    const values = filme.dataValues;
    values.id = values.cod;
    delete values.cod;

    return {
      ...values,
      url: `https://www.youtube.com/watch?v=${filme.cod}`,
    };
  });

  if (data) {
    return res.status(200).json(filmes);
  }

  return res.status(404).send(new Error("Not Found"));
};

const atualizaFilme = async (req, res) => {
  const filmeId = req.params.filmeId;

  try {
    const filme = await models.Filme.update(
      { ...req.body },
      { where: { cod: filmeId } }
    );
    return res.status(200).json(filme);
  } catch (error) {
    const filmes_obj = Object.keys(models.Filme.rawAttributes)
      .filter((key) => !models.Filme.rawAttributes[key]._autoGenerated)
      .map((key) => {
        return {
          field: models.Filme.rawAttributes[key].field,
          type: models.Filme.rawAttributes[key].type.key,
          optional: models.Filme.rawAttributes[key].allowNull !== false,
        };
      });
    if (error instanceof models.Sequelize.DatabaseError) {
      return res.status(400).json({
        error: error.message,
        expected_json: filmes_obj,
      });
    } else {
      throw new Error(error);
    }
  }
};

const apagaFilme = async (req, res) => {
  const filmeId = req.params.filmeId;

  try {
    const filme = await models.Filme.destroy({ where: { cod: filmeId } });
    return res.status(200).json(filme);
  } catch (error) {
    const filmes_obj = Object.keys(models.Filme.rawAttributes)
      .filter((key) => !models.Filme.rawAttributes[key]._autoGenerated)
      .map((key) => {
        return {
          field: models.Filme.rawAttributes[key].field,
          type: models.Filme.rawAttributes[key].type.key,
          optional: models.Filme.rawAttributes[key].allowNull !== false,
        };
      });
    if (error instanceof models.Sequelize.DatabaseError) {
      return res.status(400).json({
        error: error.message,
        expected_json: filmes_obj,
      });
    } else {
      throw new Error(error);
    }
  }
};

module.exports = {
  cadastraFilme,
  listaFilmes,
  buscaFilmeById,
  buscaFilmesPelaProdutora,
  atualizaFilme,
  apagaFilme,
};
