// const db = require("../database/db.json");
const models = require("../database/models");

const cadastraUsuario = async (req, res) => {
  try {
    const usuario = await models.Usuario.create(req.body);
    return res.status(201).json(usuario);
  } catch (error) {
    const usuario_obj = Object.keys(models.Usuario.rawAttributes)
      .filter((key) => !models.Usuario.rawAttributes[key]._autoGenerated)
      .map((key) => {
        return {
          field: models.Usuario.rawAttributes[key].field,
          type: models.Usuario.rawAttributes[key].type.key,
          optional: models.Usuario.rawAttributes[key].allowNull !== false,
        };
      });
    if (error instanceof models.Sequelize.DatabaseError) {
      return res.status(400).json({
        error: error.message,
        expected_json: usuario_obj,
      });
    } else {
      throw new Error(error);
    }
  }
};

const listaUsuarios = async (req, res) => {
  const data = await models.Usuario.findAll({});

  const usuarios = data.map((usuario) => {
    return usuario.dataValues;
  });

  return res.status(200).json(usuarios);
};

const buscaUsuarioId = async (req, res) => {
  const usuarioId = req.params.usuarioId;

  const data = await models.Usuario.findOne({ where: { id: usuarioId } });

  if (!data) {
    return res.status(404).send(new Error("Not Found"));
  }

  const usuario = data.dataValues;

  if (usuario) {
    return res.status(200).json(usuario);
  }

  return res.status(404).send(new Error("Not Found"));
};

const atualizaUsuario = async (req, res) => {
  const usuarioId = req.params.usuarioId;

  try {
    await models.Usuario.update({ ...req.body }, { where: { id: usuarioId } });
    return res.status(200).json();
  } catch (error) {
    const usuario_obj = Object.keys(models.Usuario.rawAttributes)
      .filter((key) => !models.Usuario.rawAttributes[key]._autoGenerated)
      .map((key) => {
        return {
          field: models.Usuario.rawAttributes[key].field,
          type: models.Usuario.rawAttributes[key].type.key,
          optional: models.Usuario.rawAttributes[key].allowNull !== false,
        };
      });
    if (error instanceof models.Sequelize.DatabaseError) {
      return res.status(400).json({
        error: error.message,
        expected_json: usuario_obj,
      });
    } else {
      throw new Error(error);
    }
  }
};

const apagaUsuario = async (req, res) => {
  const usuarioId = req.params.usuarioId;

  try {
    await models.Usuario.destroy({
      where: { id: usuarioId },
    });
    return res.status(200).json();
  } catch (error) {
    const usuario_obj = Object.keys(models.Usuario.rawAttributes)
      .filter((key) => !models.Usuario.rawAttributes[key]._autoGenerated)
      .map((key) => {
        return {
          field: models.Usuario.rawAttributes[key].field,
          type: models.Usuario.rawAttributes[key].type.key,
          optional: models.Usuario.rawAttributes[key].allowNull !== false,
        };
      });
    if (error instanceof models.Sequelize.DatabaseError) {
      return res.status(400).json({
        error: error.message,
        expected_json: usuario_obj,
      });
    } else {
      throw new Error(error);
    }
  }
};

const adicionaFavorito = async (req, res) => {
  const usuarioId = req.params.usuarioId;
  const filmeId = req.body.filmeId;

  try {
    const usuario = await models.Usuario.findOne({ where: { id: usuarioId } });
    if (!usuario) {
      return res.status(404).json("User Not Found");
    }
    const favoritos = usuario.dataValues.favoritos;
    favoritos.push(filmeId);

    await models.Usuario.update(
      { favoritos: favoritos },
      { where: { id: usuarioId } }
    );
    return res.status(200).json();
  } catch (error) {
    const usuario_obj = Object.keys(models.Usuario.rawAttributes)
      .filter((key) => !models.Usuario.rawAttributes[key]._autoGenerated)
      .map((key) => {
        return {
          field: models.Usuario.rawAttributes[key].field,
          type: models.Usuario.rawAttributes[key].type.key,
          optional: models.Usuario.rawAttributes[key].allowNull !== false,
        };
      });
    if (error instanceof models.Sequelize.DatabaseError) {
      return res.status(400).json({
        error: error.message,
        expected_json: usuario_obj,
      });
    } else {
      throw new Error(error);
    }
  }
};

const removeFavorito = async (req, res) => {
  const usuarioId = req.params.usuarioId;
  const filmeId = req.body.filmeId;

  try {
    const usuario = await models.Usuario.findOne({ where: { id: usuarioId } });
    if (!usuario) {
      return res.status(404).json("User Not Found");
    }
    const favoritos = usuario.dataValues.favoritos;
    const nFavoritos = favoritos.filter((filme) => filme != filmeId);

    await models.Usuario.update(
      { favoritos: nFavoritos },
      { where: { id: usuarioId } }
    );
    return res.status(200).json();
  } catch (error) {
    const usuario_obj = Object.keys(models.Usuario.rawAttributes)
      .filter((key) => !models.Usuario.rawAttributes[key]._autoGenerated)
      .map((key) => {
        return {
          field: models.Usuario.rawAttributes[key].field,
          type: models.Usuario.rawAttributes[key].type.key,
          optional: models.Usuario.rawAttributes[key].allowNull !== false,
        };
      });
    if (error instanceof models.Sequelize.DatabaseError) {
      return res.status(400).json({
        error: error.message,
        expected_json: usuario_obj,
      });
    } else {
      throw new Error(error);
    }
  }
};

const login = async (req, res) => {
  const email = req.body.email;
  const senha = req.body.senha;

  const data = await models.Usuario.findOne({
    where: { email: email, senha: senha },
  });

  if (!data) {
    return res.status(404).send(new Error("Not Found"));
  }

  const usuario = data.dataValues;

  if (usuario) {
    return res.status(200).json(usuario);
  }

  return res.status(404).send(new Error("Not Found"));
};

module.exports = {
  cadastraUsuario,
  listaUsuarios,
  buscaUsuarioId,
  atualizaUsuario,
  apagaUsuario,
  adicionaFavorito,
  removeFavorito,
  login,
};
